export const ActionType = {
    SET_LOGIN: "SET_LOGIN",
    SET_POST: "SET_POST",
    SET_LIKE: "SET_LIKE",
    SET_COMMENT: "SET_COMMENT",
    EDIT_COMMENT: "EDIT_COMMENT",
    SET_DELETE_COMMENT: "SET_DELETE_COMMENT",
    EDIT_POST: "EDIT_POST",
    SET_POST_SCROLL: "SET_POST_SCROLL",
    GOOGLE_LOGIN_DETAIL: "GOOGLE_LOGIN_DETAIL"
}